CREATE TABLE [dbo].[dnt_usergroups] (
    [groupid]            SMALLINT      IDENTITY (1, 1) NOT NULL,
    [radminid]           INT           NOT NULL,
    [type]               SMALLINT      CONSTRAINT [DF_dnt_usergroups_type] DEFAULT ((0)) NULL,
    [system]             SMALLINT      CONSTRAINT [DF_dnt_usergroups_system] DEFAULT ('0') NOT NULL,
    [grouptitle]         NVARCHAR (50) NOT NULL,
    [creditshigher]      INT           NOT NULL,
    [creditslower]       INT           NOT NULL,
    [stars]              INT           NOT NULL,
    [color]              CHAR (7)      NOT NULL,
    [groupavatar]        NVARCHAR (60) NOT NULL,
    [readaccess]         INT           NOT NULL,
    [allowvisit]         INT           NOT NULL,
    [allowpost]          INT           NOT NULL,
    [allowreply]         INT           NOT NULL,
    [allowpostpoll]      INT           NOT NULL,
    [allowdirectpost]    INT           NOT NULL,
    [allowgetattach]     INT           NOT NULL,
    [allowpostattach]    INT           NOT NULL,
    [allowvote]          INT           NOT NULL,
    [allowmultigroups]   INT           NOT NULL,
    [allowsearch]        INT           NOT NULL,
    [allowavatar]        INT           NOT NULL,
    [allowcstatus]       INT           NOT NULL,
    [allowuseblog]       INT           NOT NULL,
    [allowinvisible]     INT           NOT NULL,
    [allowtransfer]      INT           NOT NULL,
    [allowsetreadperm]   INT           NOT NULL,
    [allowsetattachperm] INT           NOT NULL,
    [allowhidecode]      INT           NOT NULL,
    [allowhtml]          INT           NOT NULL,
    [allowhtmltitle]     INT           CONSTRAINT [DF_dnt_usergroups_allowhtmltitle] DEFAULT ((0)) NOT NULL,
    [allowcusbbcode]     INT           NOT NULL,
    [allownickname]      INT           NOT NULL,
    [allowsigbbcode]     INT           NOT NULL,
    [allowsigimgcode]    INT           NOT NULL,
    [allowviewpro]       INT           NOT NULL,
    [allowviewstats]     INT           NOT NULL,
    [disableperiodctrl]  INT           NOT NULL,
    [reasonpm]           INT           NOT NULL,
    [maxprice]           SMALLINT      NOT NULL,
    [maxpmnum]           SMALLINT      NOT NULL,
    [maxsigsize]         SMALLINT      NOT NULL,
    [maxattachsize]      INT           NOT NULL,
    [maxsizeperday]      INT           NOT NULL,
    [attachextensions]   CHAR (100)    NOT NULL,
    [raterange]          NCHAR (500)   NOT NULL,
    [allowspace]         SMALLINT      CONSTRAINT [DF_dnt_usergroups_allowspace] DEFAULT ((0)) NOT NULL,
    [maxspaceattachsize] INT           CONSTRAINT [DF_dnt_usergroups_maxspaceattachsize] DEFAULT ((0)) NOT NULL,
    [maxspacephotosize]  INT           CONSTRAINT [DF_dnt_usergroups_maxspacephotosize] DEFAULT ((0)) NOT NULL,
    [allowdebate]        INT           CONSTRAINT [DF_dnt_usergroups_allowdebate] DEFAULT ((0)) NOT NULL,
    [allowbonus]         INT           CONSTRAINT [DF_dnt_usergroups_allowbonus] DEFAULT ((0)) NOT NULL,
    [minbonusprice]      SMALLINT      CONSTRAINT [DF_dnt_usergroups_minbonusprice] DEFAULT ((0)) NOT NULL,
    [maxbonusprice]      SMALLINT      CONSTRAINT [DF_dnt_usergroups_maxbonusprice] DEFAULT ((0)) NOT NULL,
    [allowtrade]         INT           CONSTRAINT [DF_dnt_usergroups_allowtrade] DEFAULT ((0)) NOT NULL,
    [allowdiggs]         INT           CONSTRAINT [DF_dnt_usergroups_allowdiggs] DEFAULT ((0)) NOT NULL,
    [modnewtopics]       SMALLINT      CONSTRAINT [DF_dnt_usergroups_modnewtopics] DEFAULT ((0)) NOT NULL,
    [modnewposts]        SMALLINT      CONSTRAINT [DF_dnt_usergroups_modnewposts] DEFAULT ((0)) NOT NULL,
    [ignoreseccode]      INT           CONSTRAINT [DF_dnt_usergroups_ignoreseccode] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dnt_usergroups] PRIMARY KEY CLUSTERED ([groupid] ASC)
);

